# Generated by Django 3.1 on 2020-10-06 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "calories_per_100",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "proteins_per_100",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("fats_per_100", models.DecimalField(decimal_places=2, max_digits=6)),
                ("carb_per_100", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[("kg", "Kilogram"), ("piece", "Piece")],
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "weight_of_pcs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="weight of an average piece / package",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="diet_composer.productcategory",
                    ),
                ),
            ],
        ),
    ]
