# Generated by Django 3.1 on 2020-10-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_composer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='carb_per_100',
            new_name='carbohydrates_per_100',
        ),
    ]
