# Generated by Django 3.1 on 2020-10-07 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201006_1855'),
        ('diet_composer', '0002_auto_20201007_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='diet_composer.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, choices=[('g', 'Gram'), ('piece', 'Piece'), ('package', 'Package')], max_length=150, null=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Depends on selected unit - grams or piece/package', max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_composer.product')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Afternoon snack', 'Snack'), ('Post-workout meal', 'Post Workout'), ('Supper', 'Supper')], max_length=50)),
                ('ingredients', models.ManyToManyField(related_name='ingredients', to='diet_composer.ProductItem')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number_of_meals', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_menus', to='users.profile')),
                ('meals', models.ManyToManyField(related_name='meals', to='diet_composer.Meal')),
            ],
        ),
    ]
