# Generated by Django 3.1 on 2020-10-07 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet_composer', '0003_auto_20201007_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_menus', to=settings.AUTH_USER_MODEL),
        ),
    ]
