# Generated by Django 3.1 on 2020-10-08 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet_composer", "0004_auto_20201007_2015"),
    ]

    operations = [
        migrations.AddField(
            model_name="productitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prod_items",
                to="diet_composer.productcategory",
            ),
        ),
        migrations.AlterField(
            model_name="dailymenu",
            name="meals",
            field=models.ManyToManyField(
                blank=True, related_name="meals", to="diet_composer.Meal"
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Breakfast", "Breakfast"),
                    ("Lunch", "Lunch"),
                    ("Dinner", "Dinner"),
                    ("Afternoon snack", "Snack"),
                    ("Post-workout meal", "Post Workout"),
                    ("Supper", "Supper"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
