# Generated by Django 3.1 on 2020-10-14 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_auto_20201014_2049"),
        ("diet_composer", "0008_auto_20201013_2023"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "piece",
                    models.DecimalField(decimal_places=1, max_digits=3, max_length=150),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.category",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="meal",
            name="recipes",
            field=models.ManyToManyField(
                related_name="meals", to="diet_composer.RecipeItem"
            ),
        ),
    ]
