# Generated by Django 3.1 on 2020-10-22 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20201014_2049'),
        ('diet_composer', '0011_auto_20201015_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Afternoon snack', 'Snack'), ('Post-workout meal', 'Post Workout'), ('Supper', 'Supper')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='recipes.recipe'),
        ),
    ]
