# Generated by Django 3.1 on 2020-10-01 18:55

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("recipes", "0003_auto_20200930_1610"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
