# Generated by Django 3.1 on 2020-10-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_auto_20201014_1756"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="total_calories",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="total_carbohydrates",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="total_fats",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="total_proteins",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
